stages:
  - extract

variables:
  GIT_COMMIT: "1" # to enable commiting report file to git
  OUTPUT_DIR: "output_dev"
extract_and_mail:
  stage: extract
  image: python:3.9
  script:
    - pip install --no-cache-dir prophecy-lineage-extractor
    - |
      # gitlab ci/cd variables, access_token also need to be defined if using git commit
      export PROPHECY_URL="$PROPHECY_URL"
      export PROPHECY_PAT="$PROPHECY_PAT"
      export SMTP_USERNAME="$SMTP_USERNAME"
      export SMTP_PASSWORD="$SMTP_PASSWORD"
      export SMTP_HOST="smtp.gmail.com"
      export SMTP_PORT="587"
      export RECEIVER_EMAIL="ashish@prophecy.io"
      # value in seconds for monitoring, this might be increased depending on pipeline size
      export MONITOR_TIME_ENV="50"
    - |
      BRANCH="dev"
      python -m prophecy_lineage_extractor \
        --project-id 36587 \
        --pipeline-id 36587/pipelines/customer_orders_demo \
        --send-email \
        --output-dir $OUTPUT_DIR \
        --branch $BRANCH
    - |
      if [ "$GIT_COMMIT" == "1" ]; then
        echo "Git commit is enabled, output directory '$OUTPUT_DIR'"
        git config --global user.name 'pateash'
        git config --global user.email 'ashishpatel0720@gmail.com'
        git add $OUTPUT_DIR/*
        git commit -m "[GitLab CI - $BRANCH] Adding excel lineage report"
        git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.com/pateash/ProphecyHelloWorld.git
        echo "Pushing changes to git branch $BRANCH"
        git push gitlab_origin HEAD:$BRANCH -o ci.skip # prevent triggering pipeline again
      else
          echo "Committing to git is not enabled"
      fi
  only:
    refs:
      - dev
