stages:
#  - setup
  - extract
#  - commit

variables:
  GIT_COMMIT: "1" # to enable commiting report file to git
  OUTPUT_DIR: "output_dev"
extract_and_mail:
  stage: extract
  image: python:3.9
  script:
    - echo "Checking PROPHECY_URL '$PROPHECY_URL'"
    - pip install --no-cache-dir prophecy-lineage-extractor
    - |
      # environment variables
      export PROPHECY_URL="$PROPHECY_URL"
      export PROPHECY_PAT="$PROPHECY_PAT"
      export SMTP_USERNAME="$SMTP_USERNAME"
      export SMTP_PASSWORD="$SMTP_PASSWORD"
      export SMTP_HOST="smtp.gmail.com"
      export SMTP_PORT="587"
      export RECEIVER_EMAIL="ashish@prophecy.io"
      # value in seconds for monitoring, this might be increased depending on pipeline size
      export MONITOR_TIME_ENV="50"
    - |
      python -m prophecy_lineage_extractor \
        --project-id 36587 \
        --pipeline-id 36587/pipelines/customer_orders_demo \
        --send-email \
        --output-dir $OUTPUT_DIR \
        --branch dev

    - git status
    - ls -la
    - echo "output directory '$OUTPUT_DIR'"
    - ls -la $OUTPUT_DIR
    - git config --global user.name 'pateash'
    - git config --global user.email 'ashishpatel0720@gmail.com'
    - echo "Committing enabled, adding output file"
    - git add $OUTPUT_DIR/*
    - git commit -m "[GitLab CI - dev] Adding excel lineage report"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.com/pateash/ProphecyHelloWorld.git
    - echo "Pushing changes to git"
    #    - git push https://oauth2:$CI_JOB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:dev
    #    - git push
    - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again

  only:
    refs:
      - dev
#
#commit_files:
#  stage: commit
##  image: alpine/git
#  script:
##    - git status
##    - ls -la
#    - echo "output directory '$OUTPUT_DIR'"
##    - ls -la $OUTPUT_DIR
##    - git config --global user.name 'pateash'
##    - git config --global user.email 'ashishpatel0720@gmail.com'
##    - echo "Committing enabled, adding output file"
##    - git add $OUTPUT_DIR/*
##    - git commit -m "[GitLab CI - dev] Adding excel lineage report"
##    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.com/pateash/ProphecyHelloWorld.git
##    - echo "Pushing changes to git"
###    - git push https://oauth2:$CI_JOB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:dev
###    - git push
##    - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again
#  dependencies:
#    - extract_and_mail
#  only:
#    refs:
#      - dev
