stages:
  - setup
  - extract
  - commit

variables:
  OUTPUT_DIR: "output_dev"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  RECEIVER_EMAIL: "ashish@prophecy.io"
  MONITOR_TIME_ENV: "50" # value in seconds for monitoring, this might be increased depending on pipeline size
  GIT_COMMIT: "1" # to enable commiting report file to git

extract_and_mail:
  stage: extract
  image: python:3.9
  variables:
    PROPHECY_URL: $PROPHECY_URL  # GitLab secret variable
    PROPHECY_PAT: $PROPHECY_PAT  # GitLab secret variable
    SMTP_USERNAME: $SMTP_USERNAME  # GitLab secret variable
    SMTP_PASSWORD: $SMTP_PASSWORD  # GitLab secret variable
  script:
    - pip install --no-cache-dir prophecy-lineage-extractor
    - |
      python -m prophecy_lineage_extractor \
        --project-id 36587 \
        --pipeline-id 36587/pipelines/customer_orders_demo \
        --send-email \
        --output-dir $OUTPUT_DIR \
        --branch dev
  only:
    refs:
      - dev

commit_files:
  stage: commit
  image: alpine/git
  script:
    - echo "output dir '$OUTPUT_DIR'"
    - echo "PROPHECY_URL: $PROPHECY_URL"
    - |
      if [[ $GIT_COMMIT == "1" ]]; then
          git config --global user.name 'pateash'
          git config --global user.email 'ashishpatel0720@gmail.com'
          echo "Committing enabled, adding output file"
          git add $OUTPUT_DIR/*
          git commit -m "[GitLab CI: dev]: Adding excel lineage report"
          echo "Pushing changes to git"
          git push
      else
          echo "Committing to git is not enabled"
      fi
  dependencies:
    - extract_and_mail
  only:
    refs:
      - dev
