name: HelloWorld
description: ''
version: 1.0.0
author: null
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: helloworld
  parentArtefactID: matthewprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-08-04 08:59:20'
pipelines:
  pipelines/customers_orders:
    name: customers_orders
    description: Aggregates total spending's for each customer
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-04 08:59:21'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-04 08:59:21'
    datasets:
      inputs:
      - datasets/customers_orders
      outputs:
      - datasets/report
    subgraphs: []
    dependencies: {}
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-04 08:59:21'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customer_totals
    subgraphs: []
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-04 08:59:21'
    datasets:
      inputs:
      - datasets/farmers-markets
      - datasets/irs-zipcode-data
      outputs:
      - datasets/farmers_market_tax_report
    subgraphs: []
    dependencies: {}
  pipelines/customer_orders_parquet_target:
    name: customer_orders_parquet_target
    description: Aggregates total spending's for each customer
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-17 10:39:15'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customer_orders_running_total
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/Test_Webscrape:
    name: Test_Webscrape
    description: ''
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-04 13:51:08'
    datasets:
      inputs:
      - datasets/poloniex_data
      outputs:
      - datasets/poloniex_trades_target
    subgraphs: []
    dependencies: {}
  pipelines/unity_catalog_example:
    name: unity_catalog_example
    description: ''
    author: ashish@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-11-19 14:26:07'
    datasets:
      inputs:
      - datasets/customer_table
      - datasets/order_table
      outputs:
      - datasets/customers_orders_table
    subgraphs: []
    dependencies: {}
datasets:
  datasets/report:
    name: report
    description: Final report for the bank
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/customers:
    name: customers
    description: All the customers
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:21'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:21'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:21'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:21'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:21'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:21'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:21'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:21'
  datasets/customer_orders_running_total:
    name: customer_orders_running_total
    description: ''
    author: matthew@prophecy.io
    createdAt: '2023-08-17 11:05:52'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-17 11:05:52'
  datasets/poloniex_data:
    name: poloniex_data
    description: ''
    author: matthew@prophecy.io
    createdAt: '2023-08-17 11:22:26'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: WebApp
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-17 11:22:26'
  datasets/poloniex_trades_target:
    name: poloniex_trades_target
    description: ''
    author: matthew@prophecy.io
    createdAt: '2023-09-05 11:46:02'
    mode: batch
    physicalDatasets:
      matt-darwin-test:
        fabricId: 4134
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-09-05 11:46:02'
  datasets/input:
    name: input
    description: ''
    author: ashish@prophecy.io
    createdAt: '2024-11-19 14:45:20'
    mode: batch
    physicalDatasets:
      ashish-fabric:
        fabricId: 1527
        datasetType: Database
        description: ''
        author: ashish@prophecy.io
        createdAt: '2024-11-19 14:45:20'
  datasets/order_table:
    name: order_table
    description: ''
    author: ashish@prophecy.io
    createdAt: '2024-11-19 14:49:52'
    mode: batch
    physicalDatasets:
      ashish-fabric:
        fabricId: 1527
        datasetType: Database
        description: ''
        author: ashish@prophecy.io
        createdAt: '2024-11-19 14:49:52'
  datasets/customer_table:
    name: customer_table
    description: ''
    author: ashish@prophecy.io
    createdAt: '2024-11-20 13:09:52'
    mode: batch
    physicalDatasets:
      ashish-fabric:
        fabricId: 1527
        datasetType: Database
        description: ''
        author: ashish@prophecy.io
        createdAt: '2024-11-20 13:09:52'
  datasets/customers_orders_table:
    name: customers_orders_table
    description: ''
    author: ashish@prophecy.io
    createdAt: '2024-11-20 13:12:56'
    mode: batch
    physicalDatasets:
      ashish-fabric:
        fabricId: 1527
        datasetType: Database
        description: ''
        author: ashish@prophecy.io
        createdAt: '2024-11-20 13:12:56'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-08-04 08:59:20'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-11-19T14:26:10.730537Z'
  name: plibMaven
  version: 8.4.0
  id: '1618510205'
  createdAt: '2024-11-19T14:26:10.730451Z'
- type: plibPypi
  modifiedAt: '2024-11-19T14:26:10.730574Z'
  name: plibPypi
  version: 1.9.24
  id: '381739042'
  createdAt: '2024-11-19T14:26:10.730564Z'
- type: pypi
  package: prophecy-spark-ai
  name: prophecy-spark-ai
  enabled: false
  id: kLobt
  entity: Project
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.34
    isDefault: true
    author: null
    createdAt: '2024-11-19 14:26:07'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-11-19 14:26:07'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
