name: HelloWorld
description: ''
version: 1.0.0
author: null
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: helloworld
  parentArtefactID: matthewprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-08-04 08:59:20'
pipelines:
  pipelines/customers_orders:
    name: customers_orders
    description: Aggregates total spending's for each customer
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-04 08:59:21'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-04 08:59:21'
    datasets:
      inputs:
      - datasets/customers_orders
      outputs:
      - datasets/report
    subgraphs: []
    dependencies: {}
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-04 08:59:21'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customer_totals
    subgraphs: []
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-04 08:59:21'
    datasets:
      inputs:
      - datasets/farmers-markets
      - datasets/irs-zipcode-data
      outputs:
      - datasets/farmers_market_tax_report
    subgraphs: []
    dependencies: {}
  pipelines/customer_orders_parquet_target:
    name: customer_orders_parquet_target
    description: Aggregates total spending's for each customer
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-17 10:39:15'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customer_orders_running_total
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/Test_Webscrape:
    name: Test_Webscrape
    description: ''
    author: matthew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-04 13:51:08'
    datasets:
      inputs:
      - datasets/poloniex_data
      outputs:
      - datasets/poloniex_trades_target
    subgraphs: []
    dependencies: {}
datasets:
  datasets/report:
    name: report
    description: Final report for the bank
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/customers:
    name: customers
    description: All the customers
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:20'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:20'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:21'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:21'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:21'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:21'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:21'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:21'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: matthew@prophecy.io
    createdAt: '2023-08-04 08:59:21'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-04 08:59:21'
  datasets/customer_orders_running_total:
    name: customer_orders_running_total
    description: ''
    author: matthew@prophecy.io
    createdAt: '2023-08-17 11:05:52'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-17 11:05:52'
  datasets/poloniex_data:
    name: poloniex_data
    description: ''
    author: matthew@prophecy.io
    createdAt: '2023-08-17 11:22:26'
    mode: batch
    physicalDatasets:
      matt-dev:
        fabricId: 3954
        datasetType: WebApp
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-08-17 11:22:26'
  datasets/poloniex_trades_target:
    name: poloniex_trades_target
    description: ''
    author: matthew@prophecy.io
    createdAt: '2023-09-05 11:46:02'
    mode: batch
    physicalDatasets:
      matt-darwin-test:
        fabricId: 4134
        datasetType: File
        description: ''
        author: matthew@prophecy.io
        createdAt: '2023-09-05 11:46:02'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-08-04 08:59:20'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: pypi
  id: kLobt
  name: prophecy-spark-ai
  enabled: false
  package: prophecy-spark-ai
projectDependencies: {}
pipelineConfigurations: {}
