from .Sum_Amounts import Sum_Amounts
from .customers_orders_table import customers_orders_table
from .inr_amount import inr_amount
from .By_CustomerId import By_CustomerId
from .report_table import report_table
from .Top_10 import Top_10
from .add_full_name import add_full_name
from .customer_orders_running_table import customer_orders_running_table
from .By_Total_Amount import By_Total_Amount
from .orders_table import orders_table
from .WindowFunction_1 import WindowFunction_1
from .Cleanup import Cleanup
from .customers_orders_table_source import customers_orders_table_source
from .customer_table import customer_table