name: Run Prophecy Lineage extractor on dev

on:
  push:
    branches:
      - dev  # Trigger on merge to the dev branch
    paths:
      - 'datasets/**'
      - 'pipelines/**'
      - 'pbt_project.yml'
      - '.github/workflows/prophecy_lineage_extractor_dev.yml'

permissions:
  contents: write

jobs:
  extract-and-mail-prophecy-lineage:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust Python version as needed

      - name: Install Package from PyPI
        run: |
          pip install --no-cache-dir prophecy-lineage-extractor==0.11.0.dev7

      - name: Extract and Send Prophecy Lineage
        run: |
          export PROPHECY_URL=https://app.prophecy.io
          export PROPHECY_PAT=${{ secrets.PROPHECY_PAT }}
          
          export SMTP_HOST=smtp.gmail.com
          export SMTP_PORT=587
          export SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          export RECEIVER_EMAIL=ashish@prophecy.io
          export OUTPUT_DIR="output_dev"
          python -m prophecy_lineage_extractor --project-id 36587 --pipeline-id 36587/pipelines/customer_orders_demo  --send-email --output-dir $OUTPUT_DIR --branch dev

      - name: Commit file to output directory
        env:
           GIT_COMMIT: ${{ vars.GIT_COMMIT }}  # Reference the GitHub variable here
        run: |
          # set this in secret to enable git commits
          echo "output dir $OUTPUT_DIR"
          if [[ $GIT_COMMIT == "1" ]]; then
              git config --global user.name 'pateash'
              git config --global user.email 'ashishpatel0720@gmail.com'
              echo "Commiting enabled, adding output file"
              git add $OUTPUT_DIR/*
              echo "========================================"
              git commit -m "[dev]: Adding excel lineage report"
              echo "========================================"
              echo "Pushing Changes to git"
              git push
          else
              # simple version are created manually from code edits.
              echo "Commiting to git is not enabled"
          fi
