name: Run Prophecy Lineage extractor

on:
  push:
    branches:
      - main  # Trigger on merge to the main branch
    paths:
      - 'datasets/**'
      - 'pipelines/**'
      - 'pbt_project.yml'
      - '.github/workflows/prophecy_lineage_extractor.yml'

permissions:
  contents: write

jobs:
  extract-and-mail-prophecy-lineage:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust Python version as needed

      - name: Install Package from PyPI
        run: |
          pip install --no-cache-dir prophecy-lineage-extractor

      - name: Extract and Send Prophecy Lineage
        run: |
          export PROPHECY_URL=https://app.prophecy.io
          export PROPHECY_PAT=${{ secrets.PROPHECY_PAT }}
          
          export SMTP_HOST=smtp.gmail.com
          export SMTP_PORT=587
          export SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          export RECEIVER_EMAIL=ashish@prophecy.io
          export OUTPUT_DIR="output"
          python -m prophecy_lineage_extractor --project-id 36587 --pipeline-id 36587/pipelines/customer_orders_demo  --send-email --output-dir $OUTPUT_DIR

      - name: Commit file to output directory
        run: |
          # set this in secret to enable git commits
          export GIT_COMMIT=${{ secrets.GIT_COMMIT }}
          if [[ $GIT_COMMIT == "1" ]]; then
              echo "Commiting enabled, adding output file"
              git add $OUTPUT_DIR/*
              echo "========================================"
              git commit -m "Adding output file"
              echo "========================================"
              echo "Pushing changes"
              git push
          else
              # simple version are created manually from code edits.
              echo "Commiting to git is not enabled"
          fi
