name: Run Prophecy Lineage extractor on main

on:
  push:
    branches:
      - main  # Trigger on merge to the main branch
    paths:
      - 'datasets/**'
      - 'pipelines/**'
      - 'pbt_project.yml'
      - '.github/workflows/prophecy_lineage_extractor.yml'

permissions:
  contents: write

jobs:
  extract-and-mail-prophecy-lineage:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: "output"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust Python version as needed

      - name: Install Package from PyPI
        run: |
          pip install --no-cache-dir prophecy-lineage-extractor

      - name: Extract and Send Prophecy Lineage
        env:
          PROPHECY_URL: "https://app.prophecy.io"
          MONITOR_TIME_ENV: ${{ vars.MONITOR_TIME_ENV }}
          PROPHECY_PAT: ${{ secrets.PROPHECY_PAT }}
          SMTP_HOST: "smtp.gmail.com"
          SMTP_PORT: "587"
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECEIVER_EMAIL: "ashish@prophecy.io"
        run: |
          python -m prophecy_lineage_extractor --project-id 36587 --pipeline-id 36587/pipelines/customer_orders_demo  --send-email --output-dir $OUTPUT_DIR

      - name: Commit file to output directory
        env:
           GIT_COMMIT: ${{ vars.GIT_COMMIT }} # whether to commit output file to github
        run: |
          # set this in secret to enable git commits
          echo "Output Directory: '$OUTPUT_DIR'"
          if [[ $GIT_COMMIT == "1" ]]; then
              git config --global user.name 'pateash'
              git config --global user.email 'ashishpatel0720@gmail.com'
              echo "Commiting enabled, adding output file"
              git add $OUTPUT_DIR/*
              echo "========================================"
              git commit -m "[Github Action: main]: Adding excel lineage report"
              echo "========================================"
              echo "Pushing Changes to git"
              git push
          else
              # simple version are created manually from code edits.
              echo "Commiting to git is not enabled"
          fi
