name: Run Prophecy Lineage extractor

on:
  push:
    branches:
      - main  # Trigger on merge to the main branch
    paths:
      - 'datasets/**'
      - 'pipelines/**'
      - 'pbt_proect.yml'
      - '.github/workflows/prophecy_lineage_extractor.yml'

permissions:
  contents: write

jobs:
  extract-and-mail-prophecy-lineage:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust Python version as needed

      - name: Install Package from PyPI
        run: |
          pip install --no-cache-dir prophecy-lineage-extractor

      - name: Extract and Send Prophecy Lineage
        run: |
          export PROPHECY_URL=https://app.prophecy.io
          export PROPHECY_PAT=${{ secrets.PROPHECY_PAT }}
          
          export SMTP_HOST=smtp.gmail.com
          export SMTP_PORT=587
          export SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          export RECEIVER_EMAIL=ashish@prophecy.io
          python -m prophecy_lineage_extractor --project-id 36587 --pipeline-id 36587/pipelines/customer_orders_demo --send-email

      - name: Commit file to output directory
        run: |
          git config --global user.name 'pateash'
          git config --global user.email 'ashishpatel0720@gmail.com'
          # current version
          GIT_COMMIT=${{ secrets.COMMIT_TO_GIT }}
          if [[ $GIT_COMMIT == "1" ]]; then
              echo "This is a dev version: $VERSION"
          else
              # simple version are created manually from code edits.
              echo "Commiting to git is not enabled"
          fi
          git add src/hckr/__about__.py
          echo "========================================"
          git commit -m "Adding output file"
          echo "========================================"
          echo "Pushing changes"
          git push
